# Generated by Django 4.2.3 on 2023-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
            },
        ),
        migrations.CreateModel(
            name='ContactInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Əlaqə nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatı',
                'verbose_name_plural': 'Əlaqə məlumatları',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ad')),
                ('surname', models.CharField(max_length=256, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Əlaqə nömrəsi')),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='OurWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ourwork_images/', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'İş',
                'verbose_name_plural': 'İşlər',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
            },
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=528, null=True, verbose_name='Banner başlığı')),
                ('banner_slogan', models.TextField(blank=True, null=True, verbose_name='Banner sloqanı')),
                ('banner_video', models.FileField(blank=True, null=True, upload_to='bannervideo/', verbose_name='Banner video')),
                ('about_company', models.TextField(blank=True, null=True, verbose_name='Şirkət haqqında')),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametrlər',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Sosial media')),
                ('link', models.URLField(max_length=528, verbose_name='Link')),
                ('icon_name', models.CharField(max_length=100, verbose_name='Ikon')),
            ],
            options={
                'verbose_name': 'Sosial media hesabı',
                'verbose_name_plural': 'Sosial media hesabları',
            },
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/', verbose_name='Şəkil')),
                ('name', models.CharField(max_length=256, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimoniallar',
            },
        ),
    ]
